[package]
name = "luminara_asset"
version.workspace = true
edition.workspace = true

[dependencies]
luminara_core = { workspace = true }
uuid = { version = "1.0", features = ["v4", "v5"] }
notify = "6.1"
crossbeam-channel = "0.5"
serde = { workspace = true }
log = "0.4"
