[package]
name = "luminara_math"
version.workspace = true
edition.workspace = true

[dependencies]
glam = { workspace = true, features = ["serde"] }
luminara_core = { workspace = true }
serde = { workspace = true }
