[package]
name = "luminara_render"
version.workspace = true
edition.workspace = true

[dependencies]
wgpu = "22"
bytemuck = { version = "1.16", features = ["derive"] }
pollster = "0.3"
log = "0.4"
luminara_core = { workspace = true }
luminara_math = { workspace = true }
luminara_window = { workspace = true }
thiserror = { workspace = true }
