[package]
name = "luminara_core"
version.workspace = true
edition.workspace = true

[dependencies]
downcast-rs = "1.2"
parking_lot = "0.12"
rayon = "1.10"
serde = { workspace = true }
log = "0.4"
instant = { workspace = true }

[dev-dependencies]
proptest = "1.5"
