[package]
name = "luminara_diagnostic"
version.workspace = true
edition.workspace = true

[dependencies]
log = "0.4"
env_logger = "0.11"
instant = { workspace = true }
luminara_core = { workspace = true }
luminara_platform = { workspace = true }
